DROP USER PROXY_SERVICE_USER;
CREATE USER PROXY_SERVICE_USER IDENTIFIED BY "change_me_proxy_pw";
GRANT CREATE SESSION TO PROXY_SERVICE_USER;
GRANT SELECT ANY DICTIONARY TO PROXY_SERVICE_USER;
GRANT SELECT ON DEMO.CUSTOMERS TO PROXY_SERVICE_USER;
GRANT SELECT ON DEMO.REFUNDS TO PROXY_SERVICE_USER;

DROP USER AI_AGENT;
CREATE USER AI_AGENT IDENTIFIED BY "change_me_agent_pw";
GRANT CREATE SESSION TO AI_AGENT;
REVOKE ALTER SYSTEM FROM AI_AGENT;
-- AI_AGENT must NOT have EXECUTE on DEMO.SQL_GUARD:
-- if it did, ALTER SESSION SET SQL_PREPROCESSOR_SCRIPT = NULL
-- followed by a direct query would bypass the guard entirely.

-- Explicitly revoke any accidental SELECT on raw CUSTOMERS.
-- AI_AGENT accesses masked data only via PROXY_SERVICE_USER → SQL_GUARD.
REVOKE SELECT ON DEMO.CUSTOMERS FROM AI_AGENT;

GRANT SELECT ON DEMO.REFUNDS TO AI_AGENT;

-- AI_AGENT_TEST: used for live privilege lockdown verification (mirrors AI_AGENT)
DROP USER AI_AGENT_TEST;
CREATE USER AI_AGENT_TEST IDENTIFIED BY "change_me_agent_pw";
GRANT CREATE SESSION TO AI_AGENT_TEST;
REVOKE ALTER SYSTEM FROM AI_AGENT_TEST;
-- AI_AGENT_TEST must NOT have EXECUTE on DEMO.SQL_GUARD (same reason as AI_AGENT above).

-- AI_AGENT_TEST intentionally receives NO direct SELECT on DEMO.CUSTOMERS.
-- Scenario 4 relies on this: even if the preprocessor session parameter is
-- bypassed (ALTER SESSION SET SQL_PREPROCESSOR_SCRIPT = NULL), the query
--   SELECT ssn FROM demo.customers
-- must fail with an object-privilege error, proving PII is unreachable at the
-- database layer — independent of any application-level guard.
REVOKE SELECT ON DEMO.CUSTOMERS FROM AI_AGENT_TEST;

GRANT SELECT ON DEMO.REFUNDS TO AI_AGENT_TEST;
